### ISSUE TITLE
fuzzfetch.FetcherException: Unknown machine for Darwin: arm64

### ISSUE THREAD

**Issue by bradwerth** [MozillaSecurity/fuzzfetch#113]
Encountered this on an M1 Max when trying to follow the command-line instructions at https://bugzilla.mozilla.org/show_bug.cgi?id=1798769#c0. Specfically, the command
```
python -m fuzzfetch --build 2db9822e6dd3 --debug --fuzzing -n firefox
```
results in this error.

**Comment by jschwartzentruber** [comment]
Sorry, we don't have M1 fuzzing builds yet, and fuzzfetch tries to get native builds by default. You can add `--cpu x86_64` to try fetching the intel version instead.
