### ISSUE TITLE
Fuzzfetch doesn't work for older verisons

### ISSUE THREAD

**Issue by sSt3lla** [MozillaSecurity/fuzzfetch#139]
Running ```fuzzfetch --build 2023-04-01```
Results in
```
Unable to find usable archive for pushdate 2023-04-01
```

**Comment by pyoor** [comment]
This is because you're trying to fetch a build that is more than a year old.  Taskcluster, the source of builds used by fuzzfetch, only archives builds for, at most, a year.  If you do `fuzzfetch --build 2023-04-01 --nearest-newer` it will retrieve the oldest available build.
