### ISSUE TITLE
Builds are not found anymore since "tar.bz2" builds got replaced with "tar.xz"

### ISSUE THREAD

**Issue by bogdanmaris** [MozillaSecurity/fuzzfetch#149]
Recent nightly builds can't be downloaded with fuzzfetch after tar.bz2 builds got changed to tar.xz.

**Comment by sylvestre** [comment]
@bogdanmaris did you update the version? 
it is supposed to be fixed here:
https://github.com/MozillaSecurity/fuzzfetch/pull/148

**Comment by bogdanmaris** [comment]
Darn, rookie mistake, I had v7.0.0. I updated to v10.0.0 and the builds are downloading now without issues. 
Sorry for the noise,
