### ISSUE TITLE
Support all platforms.

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/fuzzfetch#3]
Need to add support for win32/64 & linux32 builds.

[DOMFuzz](https://github.com/MozillaSecurity/domfuzz/blob/master/util/downloadBuild.py) may be useful as a reference.

This should also include overriding which platform you want (eg. downloading 32-bit on a 64-bit platform).

**Comment by nth10sd** [comment]
Note that [funfuzz](https://github.com/MozillaSecurity/funfuzz/blob/87e84d74fe53318b784a02b4a75fed8d9f6f0abf/util/downloadBuild.py) also has downloadBuild (that I'm barely maintaining), since DOMFuzz forked out from funfuzz.

When fuzzfetch gets feature parity with downloadBuild, I'll likely remove downloadBuild (and the forked version of tooltool we have, urgh).

**Comment by kkuehl** [comment]
I have noticed that the domfuzz/funfuzz downloadBuild.py script only downloads a very old version of firefox.

    python ./domfuzz/util/downloadBuild.py --want-tests
    ./build/dist/bin/firefox -v
    Mozilla Firefox 49.0a1

It seems the downloadBuild.py tries this directory:
[mozilla-central-linux64-debug](https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-linux64-debug/)
Then finds
[1462971250](https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-linux64-debug/1462971250/)
as the latest.

If I use fuzzfetch:

    python -m fuzzfetch -d -n /build --tests common reftests gtest
    ./build/dist/bin/firefox -v
    Mozilla Firefox 57.0a1

I can get a nightly build that seems to work okay with domfuzz, but I get a few more errors than the old build.
A quick test indicates that the nightly is working okay with domfuzz, although I see more errors/warnings than usual. Are the nightlie compatible with domfuzz?

**Comment by nth10sd** [comment]
downloadBuild.py in funfuzz supports only archive.mozilla.org (formerly ftp.mozilla.org), and the current implementation will be overhauled eventually. The reason why the very old build is obtained is likely the fault of the server - Mac and Linux builds served by it are months/years-old as those directories are no longer updated on the server side.

fuzzfetch is the new thing that works with TaskCluster builds, and downloadBuild will use/be supplanted by fuzzfetch.

Note that domfuzz is on low-maintenance mode.

**Comment by jschwartzentruber** [comment]
@kkuehl fuzzfetch is intended to download builds that work with domfuzz/funfuzz, but there are lots of cases we're not testing yet. If you find any bugs, please create issues here :-)

**Comment by pyoor** [comment]
At this point, fuzzfetch supports all builds indexed by taskcluster.  If you identify a build type that is not supported, please open an issue for that build directly.
