### ISSUE TITLE
Use 7z for decompression if available.

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/fuzzfetch#42]
Using 7z instead of libbz2 is about twice as fast due to multi-threading. We should use 7z in a sub-process if it is installed.

**Comment by jschwartzentruber** [comment]
Here's some examples. The third case would likely be the easiest way since we could still use Python's tarfile module.

<pre>
$ time <b>tar xaf target.tar.bz2</b>
tar xaf target.tar.bz2  31.78s user 1.93s system 104% cpu <b>32.290</b> total

$ time <b>bzcat target.tar.bz2 | tar x</b>
bzcat target.tar.bz2  33.25s user 0.49s system 99% cpu <b>33.836</b> total
tar x  0.22s user 1.54s system 5% cpu 33.835 total

$ time <b>7z x target.tar.bz2</b> && time <b>tar xf target.tar</b>
7z x target.tar.bz2  33.12s user 0.62s system 183% cpu <b>18.404</b> total
tar xf target.tar  0.13s user 1.10s system 29% cpu <b>4.117</b> total

$ time <b>7z x -so target.tar.bz2 | tar x</b>
7z x -so target.tar.bz2  30.92s user 0.43s system 178% cpu <b>17.532</b> total
tar x  0.07s user 1.25s system 7% cpu 17.529 total
</pre>

**Comment by nth10sd** [comment]
I sometimes use `tar cvJf <file to be created> <files to add>` - note the capital J for .xz format. Is this relevant?

Moreover the `tarfile` module since version 3.3 has support for xz too.

**Comment by jschwartzentruber** [comment]
This is fixed in 3cb956dc20ac6ca1d132d37a292239972dc1377f.
