### ISSUE TITLE
Add support for spidermonkey-only builds

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/fuzzfetch#59]
eg. https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.firefox/sm-fuzzing-linux64

These are packaged very differently.

**Comment by pyoor** [comment]
I'm going to reach out to the JS team and see if we can't get them to include a target.json file for these builds.  If so, we should still be able to fetch them with minimal effort.

**Comment by nth10sd** [comment]
Maybe try asking :sfink on the JS team? I know he has had experience on SpiderMonkey CI builds previously.

**Comment by pyoor** [comment]
Spoke with :sfink tonight - these builds don't go through the normal build packaging and as such, doesn't allow us to leverage them to generate those files.  He's going to look into it tomorrow but mentioned that he should be able to generate the data we need in the target.json format.

**Comment by pyoor** [comment]
Minimal target.json support for spidermonkey builds landed in https://bugzilla.mozilla.org/show_bug.cgi?id=1603627

**Comment by jschwartzentruber** [comment]
Initial support for sm builds landed in #100 (release 1.3.0)
