### ISSUE TITLE
Windows ASAN opt builds are old

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/fuzzfetch#7]
Both `fuzzfetch -a` and `fuzzfetch --inbound -a` return old builds on win64.

https://ci.appveyor.com/project/MozillaSecurity/fuzzfetch/build/1.0.5/job/kjs7wslmyyn5894k

**Comment by pyoor** [comment]
@tysmith reported this recently - https://bugzilla.mozilla.org/show_bug.cgi?id=1394543
